import { json } from "react-router-dom";
const employees = [
  {
    employeeId: 123,
    email: "employee123@example.com",
    password: "123",
    firstName: "Aarav",
    countTask: {
      failed: 1,
      active: 1,
      complete: 2,
      newTask: 2,
    },
    tasks: [
      {
        taskId: 1,
        title: "Complete Project Report",
        description: "Prepare and submit the project report by end of day.",
        category: "Report",
        status: "complete",
        date: "2024-10-28",
        failed: false,
        active: false,
        complete: true,
        newTask: false,
      },
      {
        taskId: 2,
        title: "Email Client Updates",
        description: "Send monthly updates to all clients.",
        category: "Communication",
        status: "new",
        date: "2024-10-27",
        failed: false,
        active: false,
        complete: false,
        newTask: true,
      },
      {
        taskId: 3,
        title: "Team Meeting Preparation",
        description: "Prepare the agenda for the upcoming team meeting.",
        category: "Meeting",
        status: "active",
        date: "2024-10-29",
        failed: false,
        active: true,
        complete: false,
        newTask: false,
      },
      {
        taskId: 4,
        title: "Budget Analysis",
        description:
          "Analyze the current quarter budget and prepare a summary report.",
        category: "Finance",
        status: "failed",
        date: "2024-10-20",
        failed: true,
        active: false,
        complete: false,
        newTask: false,
      },
      {
        taskId: 5,
        title: "Product Launch Strategy",
        description:
          "Develop a strategic plan for the upcoming product launch.",
        category: "Strategy",
        status: "complete",
        date: "2024-10-15",
        failed: false,
        active: false,
        complete: true,
        newTask: false,
      },
      {
        taskId: 6,
        title: "Market Research",
        description: "Conduct research on market trends for the new product.",
        category: "Research",
        status: "new",
        date: "2024-11-01",
        failed: false,
        active: false,
        complete: false,
        newTask: true,
      },
      {
        taskId: 7,
        title: "Customer Feedback Analysis",
        description: "Analyze customer feedback data from last quarter.",
        category: "Analysis",
        status: "active",
        date: "2024-10-30",
        failed: false,
        active: true,
        complete: false,
        newTask: false,
      },
    ],
  },
  {
    employeeId: 124,
    email: "employee124@example.com",
    password: "123",
    firstName: "Ishaan",
    countTask: {
      failed: 0,
      active: 1,
      complete: 1,
      newTask: 0,
    },
    tasks: [
      {
        taskId: 1,
        title: "Client Meeting Preparation",
        description: "Gather materials for the client meeting.",
        category: "Meeting",
        status: "active",
        date: "2024-10-29",
        failed: false,
        active: true,
        complete: false,
        newTask: false,
      },
      {
        taskId: 2,
        title: "Update Financial Records",
        description: "Ensure records are updated for quarterly review.",
        category: "Finance",
        status: "complete",
        date: "2024-10-25",
        failed: false,
        active: false,
        complete: true,
        newTask: false,
      },
    ],
  },
  {
    employeeId: 125,
    email: "employee125@example.com",
    password: "123",
    firstName: "Sneha",
    countTask: {
      failed: 1,
      active: 0,
      complete: 0,
      newTask: 1,
    },
    tasks: [
      {
        taskId: 1,
        title: "Code Review",
        description: "Review recent commits and approve changes.",
        category: "Development",
        status: "failed",
        date: "2024-10-26",
        failed: true,
        active: false,
        complete: false,
        newTask: false,
      },
      {
        taskId: 2,
        title: "Team Building Activity",
        description: "Organize a team activity to foster collaboration.",
        category: "HR",
        status: "new",
        date: "2024-10-30",
        failed: false,
        active: false,
        complete: false,
        newTask: true,
      },
    ],
  },
  {
    employeeId: 126,
    email: "employee126@example.com",
    password: "123",
    firstName: "Pooja",
    countTask: {
      failed: 0,
      active: 1,
      complete: 1,
      newTask: 0,
    },
    tasks: [
      {
        taskId: 1,
        title: "Prepare Presentation Slides",
        description: "Create slides for the upcoming client presentation.",
        category: "Presentation",
        status: "active",
        date: "2024-10-28",
        failed: false,
        active: true,
        complete: false,
        newTask: false,
      },
      {
        taskId: 2,
        title: "Finalize Budget Proposal",
        description: "Complete and submit the budget proposal.",
        category: "Finance",
        status: "complete",
        date: "2024-10-24",
        failed: false,
        active: false,
        complete: true,
        newTask: false,
      },
    ],
  },
  {
    employeeId: 127,
    email: "employee127@example.com",
    password: "123",
    firstName: "Ravi",
    countTask: {
      failed: 0,
      active: 1,
      complete: 0,
      newTask: 1,
    },
    tasks: [
      {
        taskId: 1,
        title: "Market Research",
        description: "Conduct research on emerging market trends.",
        category: "Research",
        status: "new",
        date: "2024-10-31",
        failed: false,
        active: false,
        complete: false,
        newTask: true,
      },
      {
        taskId: 2,
        title: "Update Social Media Content",
        description: "Plan and update content across social media platforms.",
        category: "Marketing",
        status: "active",
        date: "2024-10-27",
        failed: false,
        active: true,
        complete: false,
        newTask: false,
      },
    ],
  },
];

const admin = {
  adminId: 1,
  email: "admin@a.com",
  password: "123",
  firstName: "John",
};


export const setLocalStorage = () => {
  localStorage.setItem('employees', JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export const gettLocalStorage = () => {
  const admin = JSON.parse(localStorage.getItem("admin"));
  const employees = JSON.parse(localStorage.getItem("employees"));

  return ({ employees, admin });
};